### ISSUE TITLE
REST API connection refused

### ISSUE THREAD

**Issue by teaglebuilt** [radarlabs/documentation#181]
Can someone help me, I cannot get past the authentication using the api token in the Authorization header. Is there something else that needs to be done? I am using the correct key. I am getting connection refused

```
❯ curl https://api.radar.io/v1/users \
  -H "Authorization: prj_live_sk_*****************"

curl: (7) Failed to connect to api.radar.io port 443: Connection refused
```

**Comment by jsani-radar** [comment]
hey @teaglebuilt, apologies for the late reply here

unfortunately, I'm unable to repro your issue, so it's likely that it's an issue with your machine's outbound connection to our servers, rather than a problem with Radar generating a response

<img width="1002" alt="Screenshot 2023-03-06 at 3 58 01 PM" src="https://user-images.githubusercontent.com/58698757/223229090-4f138b6e-ee44-48ba-b47f-dcd77d1e91d9.png">
